FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /app

# Install Python
RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    rm -rf /var/lib/apt/lists/*

# Install pip packages
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt



